import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Prof. NOTA's Deep Links</title>
        <link rel="icon" href="/1.47.png" />
        <link rel="apple-touch-icon" href="/1.47.png" />
        <link rel="shortcut icon" href="/1.47.png" />
        <meta
          name="description"
          content="Please note that this link merely provides a list of Prof. NOTA's Deep Links and does not facilitate the access to or use of the Deep Links."
        />
        <meta name="author" content="! Prof. NOTA !" />
        <meta
          name="keywords"
          content="the melting land, linktree, prof. nota, uncertified professor, my receipt, myreceipt, blockchain, web3, smart contract, retired developer, non-fungible token, nonfungible token, nft, ethereum, polygon, tezos, solana, bitcoin,"
        />
        
      </Head>

      <main>
        <h1 className={styles.title}>
          Deep Links of&nbsp;
          <a href="https://prompt.straight-line.org" target="_blank">
            Prof. NOTA
          </a>{" "}
          {/* <code>deep_links</code> */}
        </h1>

        <p className={styles.description}>
          The Initiator of{" "}
          <a href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/48.-init...-_" target="_blank">
            The Melting Land
          </a>
        </p>

        <social>
          <a
            href="https://twitter.com/MyReceiptTT"
            target="_blank"
            title="Go visit @MyReceiptTT, Prof. NOTA's Twitter account."
          >
            <img src="/twitter.svg" alt="Prof. NOTA v.1.47" className={styles.icon} />
          </a>&nbsp;
          <a
            href="https://api.whatsapp.com/send?phone=628563160756&amp;text=Hi%20Prof.%20NOTA!!!!%0A%F0%9F%A4%AB%F0%9F%A4%AB%F0%9F%A4%AB%F0%9F%A4%AB%20Shush%2C%20I%20need%20to%20talk%20with%20you!%20Okay!" 
            target="_blank"
            title="Go contact Prof. NOTA's Whatsapp account."
          >
            <img src="/whatsapp.svg" alt="Prof. NOTA v.1.47" className={styles.icon} />
          </a>&nbsp;
          <a
            href="https://instagram.com/myreceipt"
            target="_blank"
            title="Go visit @MyReceipt, Prof. NOTA's Instagram account."
          >
            <img src="/instagram.svg" alt="Prof. NOTA v.1.47" className={styles.icon} />
          </a>&nbsp;
        </social>

        <div className={styles.grid}>
          <a
            href="https://opensea.io/collection/deth-wish-in-vision-trip/drop?tab=mint"
            className={styles.card}
            target="_blank"
          >
            <h3>2nd /&#x02C8;deTH ˌwiSH/ (PFP Drop) &rarr;</h3>
            <p>Visible or not, there is always a /&#x02C8;deTH ˌwiSH/ in their minds. (13_!)</p>
          </a>

          <a
            href="https://heartx.art/artwork/2003928"
            className={styles.card}
            target="_blank"
          >
            <h3>2nd /&#x02C8;deTH ˌwiSH/ on HeartX &rarr;</h3>
            <p>An opening artwork released as 1/1 NFT on HeartX just for you. (13_!)</p>
          </a>

          <a
            href="https://generative.xyz/generative/1002498"
            className={styles.card}
            target="_blank"
          >
            <h3>NOTA&#39;s Ordinals &rarr;</h3>
            <p>47 Prof. NOTA's Ordinals to rule all the 47 avatars of Prof. NOTA. (17_!)</p>
          </a>

          <a
            href="https://generative.xyz/generative/1002511"
            className={styles.card}
            target="_blank"
          >
            <h3>NOTA&#39;s SVGs Free &rarr;</h3>
            <p>NOTA's SVGs are very limited, only seven items with different colors. (17_!)</p>
          </a>

          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/18.-my-receipt-of-xtz"
            className={styles.card}
            target="_blank"
          >
            <h3>MY RECEIPT of XTZ &rarr;</h3>
            <p>This collection only contains open-edition Tezos NFTs by Prof. NOTA. (18)</p>
          </a>

          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/19.-panthera-leo"
            className={styles.card}
            target="_blank"
          >
            <h3>Panthera LEO NFTs &rarr;</h3>
            <p>
              74 NFTs of 1/1 A.I. art generated by Prof. NOTA v.6.0 (6 years old). (19_!)</p>
          </a>

          {/* <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/20.-my-receipt-of-eth"
            className={styles.card}
            target="_blank"
          >
            <h3>MY RECEIPT of ETH &rarr;</h3>
            <p>This collection only contains open-edition Ethereum NFTs by Prof. NOTA. (20)</p>
          </a> */}

          <a
            href="https://app.manifold.xyz/c/unrevealed"
            className={styles.card}
            target="_blank"
          >
            <h3>OFFICIALLY UNREVEALED &rarr;</h3>
            <p>Stay unrevealed, stay under the hood, and always use your pseudonymous mask. (20_!)</p>
          </a>

          <a
            href="https://app.manifold.xyz/c/beware-of-scams"
            className={styles.card}
            target="_blank"
          >
            <h3>PROF. NOTA&#39;S PFP &rarr;</h3>
            <p>If you can, please always keep our community safe and beware of scams! (20_!)</p>
          </a>
          
          {/* <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/22.-bananow-nfts"
            className={styles.card}
            target="_blank"
          >
            <h3>BANANOW NFTs &rarr;</h3>
            <p>NFTs that are used as entry-pass to access the rich of BANANOW.LAND. (22_!)</p>
          </a> */}

          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/24.-conserve-roty-broi"
            className={styles.card}
            target="_blank"
          >
            <h3>CONSERVE ROTY BROI &rarr;</h3>
            <p>NFTs of physical artworks by various traditional artists in BALI island. (24_!!)</p>
          </a>

          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/30.-impromptu"
            className={styles.card}
            target="_blank"
          >
            <h3>! IMPROMPTU ! NFTs &rarr;</h3>
            <p>A collection that contains impromptu collaborative work with Humans and A.I. (30_!!)</p>
          </a>
          
          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/31.-0101-of-prof.-nota"
            className={styles.card}
            target="_blank"
          >
            <h3>0101 of Prof. NOTA &rarr;</h3>
            <p>This 0101 of Prof. NOTA will contain ONE-on-ONE artworks by Prof. NOTA. (31)</p>
          </a>
          
          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1/43.-logo-pabrik-roti"
            className={styles.card}
            target="_blank"
          >
            <h3>Breads Factory Logo &rarr;</h3>
            <p>May you be the lucky ones, you get Her rarest assets. It's up to you! (43_!)</p>
          </a>
          
          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-1"
            className={styles.card}
            target="_blank"
          >
            <h3>WAIVFVES #1 Mapping &rarr;</h3>
            <p>All the information about the creations in WAIVFVES #1 of The KING's NFTs.</p>
          </a>
          
          <a
            href="https://iqraa.straight-line.org/the-kings-nfts/02-the-creations.../waivfves-2"
            className={styles.card}
            target="_blank"
          >
            <h3>WAIVFVES #2 Mapping &rarr;</h3>
            <p>All the information about the creations in WAIVFVES #2 of The KING's NFTs.</p>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://iqraa.straight-line.org/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img src="/1.47.svg" alt="Prof. NOTA v.1.47" className={styles.logo} />
          {" "}© All rights belong to Prof. NOTA ©{" "}
          <img src="/1.47.svg" alt="Prof. NOTA v.1.47" className={styles.logo} />
        </a>
      </footer>

      <style jsx>{`
        main {
          padding: 4.7rem 0 1.47rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }

        social {
          display: flex;
          justify-content: center;
          align-items: center;
        }
        footer {
          width: 100%;
          height: 100px;
          border-top: 1px solid #eaeaea;
          display: flex;
          justify-content: center;
          align-items: center;
          font-size: x-small;
        }
        @media (min-width: 425px) {
          footer {
            font-size: small;
          }
        }
        @media (min-width: 640px) {
          footer {
            font-size: medium;
          }
        }
        footer img {
          margin-left: 0.5rem;
          margin-right: 0.5rem;
        }
        footer a {
          display: flex;
          justify-content: center;
          align-items: center;
          text-decoration: none;
          color: inherit;
        }
        footer a:hover {
          color: yellow;
          text-decoration: underline;
        }
        code {
          background: #fafafa;
          border-radius: 5px;
          padding: 0.75rem;
          font-size: 1.1rem;
          font-family: Fira Code, monospace;
        }
      `}</style>

      <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: Fira Code, monospace;
        }
        * {
          box-sizing: border-box;
        }
      `}</style>
    </div>
  );
}
